<?php

namespace App\Utils;

use Doctrine\Persistence\ManagerRegistry;
use Doctrine\Persistence\ObjectManager;
use DateTime;
use App\Repository\CoutsRepository;
use App\Entity\Couts;


class Globals
{
    private ManagerRegistry $managerRegistry;
    public CoutsRepository $coutsRepo;

    public function  __construct(ManagerRegistry $managerRegistry, CoutsRepository $coutsRepo)
    {
        $this->managerRegistry = $managerRegistry;
        $this->coutsRepo = $coutsRepo;
    }


    public function em() : ObjectManager
    {
        return $this->managerRegistry->getManager();
    }

    /**
     * @return false|string
     */
    public function MoiEnCours()
    {
        setlocale(LC_TIME, "fr_FR");
        $mois = strftime("%B");
        if($mois == 'January')
            return 'Janvier';

        if($mois == 'Febuary')
            return 'Février';

        if($mois == 'March')
            return 'Mars';

        if($mois == 'April')
            return 'Avril';

        if($mois == 'May')
            return 'Mai';

        if($mois == 'June')
            return 'Juin';

        if($mois == 'July')
            return 'Juillet';

        if($mois == 'August')
            return 'Août';

        if($mois == 'September')
            return 'Septembre';

        if($mois == 'October')
            return 'Octobre';

        if($mois == 'November')
            return 'Novembre';

        if($mois == 'December')
            return 'Décembre';
    }


    /**
     * @return string
     */
    public function monthFromDate($mois)
    {
        if($mois == '01')
            return 'Janvier';

        if($mois == '02')
            return 'Février';

        if($mois == '03')
            return 'Mars';

        if($mois == '04')
            return 'Avril';

        if($mois == '05')
            return 'Mai';

        if($mois == '06')
            return 'Juin';

        if($mois == '07')
            return 'Juillet';

        if($mois == '08')
            return 'Août';

        if($mois == '09')
            return 'Septembre';

        if($mois == '10')
            return 'Octobre';

        if($mois == '11')
            return 'Novembre';

        if($mois == '12')
            return 'Décembre';
    }


    /**
     * @return string
     */
    public function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}